# https://taskfile.dev

version: "3"
vars:
  PROJECT_NAME: AoC_2024
tasks:
  default:
    desc: Prints this message
    cmds:
      - cmd: task --list-all
  build:doc:
    desc: Builds documentation using ocamldoc
    preconditions:
      - which ocamldoc
    cmds:
      - cmd: ocamldoc -html -d docs bin/main.ml
    silent: true
  build:
    desc: Builds the project
    preconditions:
      - which dune
    cmds:
      - cmd: dune build
  test:
    desc: Runs the tests in the 'tests' directory
    ignore_error: true
    env:
      OUNIT_CI: true
    preconditions:
      - which dune
    deps:
      - task: build
    cmds:
      - cmd: dune test {{.CLI_ARGS}}
  test:watch:
    desc: Continuously runs the tests in the 'tests' directory
    ignore_error: true
    sources:
      - lib/**/*.ml
      - test/**/*.ml
    env:
      OUNIT_CI: true
    preconditions:
      - which dune
    deps:
      - task: build
    cmds:
      - cmd: dune test --watch {{.CLI_ARGS}}
  run:
    desc: Runs the project
    preconditions:
      - which dune
    deps:
      - task: build
    cmds:
      - cmd: dune exec {{.PROJECT_NAME}}
